### ISSUE TITLE
Comdirect cdv export format

### ISSUE THREAD

**Issue by philippvogler** [khujo/comdirect-to-ynab#2]
Hi Felix! Offenbar hat es Comdirect irgendwann zwischen dem 01 und dem 20. April geschafft das Format der csv Dateien zu ändern. Bisher waren die ; separiert, nun scheinen die , separiert zu sein. Dein wunderbarer Importer funktioniert jetzt leider nicht mehr oder zumindest nicht so schön einfach wie vorher. Grüße,Philipp

**Comment by khujo** [comment]
Moin Philipp,

leider ist das CSV Format der comdirect recht chaotisch. Tatsächlich haben sie nicht das Trennzeichen ausgetauscht, sie haben es jetzt zwischen Buchungstext und Umsatz schlicht vergessen. Außerdem sind wild irgendwelche Leerzeichen hinzugekommen oder verschwunden.

Ich habe den Parser angepasst und eine neue Version hochgeladen. Versuche die Seite einmal mit Str+F5 neu zu laden, dann sollte es wieder gehen.

Gruß
Felix
